version : '3'

services:
  web:
   # container_name: contenedor-tarea3
    build: .
    
    ports:
      - "5001:5001"
    volume: 
      -.:/app
    environment:
      - FLASK_APP=app/app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5001 

