name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: pip install -r app/requirements.txt

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

       

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets._GITHUB_TOKEN }}
          publish_dir: ./build  

#  deploy:
#    needs: build-and-test
#    runs-on: ubuntu-latest
#    steps:
#      - name: Log in to Docker Hub
#        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#      
#      - name: Build and push Docker image
#        run: |
#          docker build -t your-dockerhub-edu415ag/flask-app:latest .
#          docker push your-dockerhub-edu415ag/flask-app:latest
